$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceDir = Join-Path $scriptDir 'dist\win-unpacked'
$outputFile = Resolve-Path -Path (Join-Path $scriptDir '..\data\downloads\HHRP Launcher Setup.exe') -ErrorAction SilentlyContinue
if (-not $outputFile) { $outputFile = Join-Path $scriptDir '..\data\downloads\HHRP Launcher Setup.exe' }

$iexpress = Get-Command iexpress.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
if (-not $iexpress) {
    Write-Error "iexpress.exe wurde nicht gefunden. Dieses System scheint IExpress nicht installiert zu haben."
    exit 1
}

if (-not (Test-Path $sourceDir)) {
    Write-Error "Quelldateien für den Installer wurden nicht gefunden: $sourceDir"
    exit 1
}

# Prepare temp working directory
$temp = Join-Path $env:TEMP ("hhrp-iexpress-{0}" -f ([guid]::NewGuid().ToString()))
$filesDir = Join-Path $temp 'Files'
New-Item -Path $filesDir -ItemType Directory -Force | Out-Null
# Persist temp path for debugging
Set-Content -Path (Join-Path $scriptDir 'last-iexpress-temp.txt') -Value $temp -Encoding UTF8

Write-Output "Kopiere Dateien nach $filesDir ..."
Copy-Item -Path (Join-Path $sourceDir '*') -Destination $filesDir -Recurse -Force

# Create install.ps1 (runs on target machine)
$installPs1 = @'
$installDir = Join-Path $env:ProgramFiles "HHRP Launcher"
if (-not (Test-Path $installDir)) { New-Item -ItemType Directory -Path $installDir -Force | Out-Null }

# Copy all extracted files to Program Files
$source = Split-Path -Parent $MyInvocation.MyCommand.Path
Copy-Item -Path (Join-Path $source '*') -Destination $installDir -Recurse -Force

# Create shortcuts
$WshShell = New-Object -ComObject WScript.Shell
$startMenu = Join-Path $env:ProgramData "Microsoft\Windows\Start Menu\Programs\HHRP Launcher"
if (-not (Test-Path $startMenu)) { New-Item -ItemType Directory -Path $startMenu -Force | Out-Null }

$exePath = Join-Path $installDir 'HHRP Launcher.exe'
$lnk = $WshShell.CreateShortcut((Join-Path $startMenu 'HHRP Launcher.lnk'))
$lnk.TargetPath = $exePath
$lnk.WorkingDirectory = $installDir
$lnk.Save()

$desktop = [Environment]::GetFolderPath('Desktop')
$lnk2 = $WshShell.CreateShortcut((Join-Path $desktop 'HHRP Launcher.lnk'))
$lnk2.TargetPath = $exePath
$lnk2.WorkingDirectory = $installDir
$lnk2.Save()

# Write simple uninstall script
$uninstallPath = Join-Path $installDir 'Uninstall HHRP Launcher.ps1'
@"
# Uninstall script generated by installer
Remove-Item -Recurse -Force '$installDir'
Remove-Item -Force (Join-Path '$startMenu' 'HHRP Launcher.lnk') -ErrorAction SilentlyContinue
Remove-Item -Force (Join-Path '$desktop' 'HHRP Launcher.lnk') -ErrorAction SilentlyContinue
"@ | Out-File -FilePath $uninstallPath -Encoding UTF8

Write-Output "Installation abgeschlossen."
'@

$installPs1Path = Join-Path $filesDir 'install.ps1'
$installPs1 | Out-File -FilePath $installPs1Path -Encoding UTF8

# Create install.cmd that launches the PowerShell installer script
$installCmd = 'powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0install.ps1"'
$installCmdPath = Join-Path $filesDir 'install.cmd'
$installCmd | Out-File -FilePath $installCmdPath -Encoding ASCII

# Build SED file listing all files under Files
$sedPath = Join-Path $temp 'package.sed'
$targetAbsolute = [System.IO.Path]::GetFullPath($outputFile)

$sedHeader = @(
"[Version]",
"Class=IEXPRESS",
"SEDVersion=3",
"",
"[Options]",
"PackagePurpose=InstallApp",
"ShowInstallProgramWindow=1",
"HideExtractAnimation=0",
"UseLongFileName=1",
"InsideCompressed=0",
"CAB_FixedSize=0",
"RebootMode=NoRestart",
"InstallPrompt=",
"DisplayName=HHRP Launcher",
"FinishMessage=Die Installation wurde abgeschlossen.",
"TargetName=$targetAbsolute",
"FriendlyName=HHRP Launcher",
"PostInstallCmdLine=install.cmd",
"CompressionType=MSZIP",
"",
"[SourceFiles]",
"SourceFiles0=Files",
"",
"[SourceFiles0]"
)

# Collect files recursively and add entries
$files = Get-ChildItem -Path $filesDir -Recurse -File | ForEach-Object { $_.FullName.Substring($filesDir.Length+1) }
$idx = 1
$sedBody = @()
foreach ($f in $files) {
    $sedBody += ("File{0}={1}" -f $idx, (Join-Path 'Files' $f))
    $idx++
}

$sedContent = $sedHeader + $sedBody
$sedContent | Out-File -FilePath $sedPath -Encoding ASCII

# Run iexpress
Push-Location $temp
Write-Output "Erzeuge IExpress-Paket..."
& "$iexpress" /N "$sedPath"
$exit = $LASTEXITCODE
Pop-Location

if ($exit -ne 0) {
    Write-Error "IExpress meldete einen Fehler (Exit-Code $exit)."
    exit $exit
}

# Move generated installer to desired output path if not already
$generated = Get-ChildItem -Path $temp -Filter '*.exe' | Select-Object -First 1
if ($generated) {
    $dest = (Resolve-Path -Path $outputFile -ErrorAction SilentlyContinue)
    if (-not $dest) {
        Copy-Item -Path $generated.FullName -Destination $outputFile -Force
    }
    Write-Output "Installer erstellt: $outputFile"
} else {
    Write-Error "Konnte erstellte EXE nicht finden."
    exit 2
}

# Cleanup
# Remove-Item -Recurse -Force $temp

Write-Output "Fertig."